### ISSUE TITLE
[bug] Logout crashing website

### ISSUE THREAD

**Issue by jain-arihant-2002** [jain-arihant-2002/HMS_Client#1]
Logout should redirect to "/" instead just change state
![image](https://github.com/jain-arihant-2002/HMS_Client/assets/91581141/cedda07a-3696-44c2-8c24-3fac0447019c)

**Comment by saheemshafi** [comment]
Add a `_redirects` file in your public folder.
now copy paste this code to _redirects file.
```
/* /index.html 200
```

The reason for the problem is that `react-router` uses *Javascript* to transition paths/routes and loads the required content on the same `index.html` without ever actually changing the route hence, SPA(single page application).
But netlify by default forces it into a different route like a multipage app resulting in this issue.

**Comment by jain-arihant-2002** [comment]
Thanks for explanation and solution. Solution is implemented and solved thanks to you.
